import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

const browser = await chromium.launch({channel:'msedge',headless:true});
const page = await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await fs.mkdir('test-results-hub',{recursive:true});
try {
  await page.goto(process.env.GLORB_URL || 'http://127.0.0.1:43220/three-js');
  await expect(page.locator('#preloader')).toBeHidden({timeout:90000});
  await page.getByRole('button',{name:'GO GO GO',exact:true}).click();
  for(const text of ['HELLO HELLO HELLO HELLO','WE FOUND MORE LAND TO PAINT','ARE YOU COMING']) {
    const bubble=page.locator('.dialog-bubble').filter({hasText:text}).last();
    await expect(bubble.locator('.bubble')).toHaveClass(/is-done/,{timeout:40000});
    await page.keyboard.press('Space');
  }
  await page.getByRole('button',{name:'YES YES YES',exact:true}).click();
  await expect(page.locator('.dialog-bubble').filter({hasText:'GLORB'}).last().locator('.bubble')).toHaveClass(/is-done/,{timeout:40000});
  await page.keyboard.press('Space');
  await expect(page.getByRole('button',{name:'Enter Level One',exact:true})).toBeVisible({timeout:90000});
  const snapshot = () => page.evaluate(()=>{
    const a=window.__THREE_JS_GAME__.app;
    const p=a.$webgl.scenes.current.player;
    return {hub:a.__hub.active,phase:a.__survival.run.phase,time:a.__survival.run.elapsed,health:a.__survival.run.health,paint:a.__paintState.ratio,camera:{elevation:p.cameraOptions.elevation,distance:p.cameraOptions.distance,intersectGround:p.cameraOptions.intersectGround},position:{x:p.base.position.x,z:p.base.position.z},canMove:p.canMove};
  });
  await page.waitForTimeout(1000);
  const hub=await snapshot();
  assert.equal(hub.hub,true);
  assert.ok(hub.camera.elevation>=3.7&&hub.camera.elevation<=4);
  assert.ok(hub.camera.distance>=8&&hub.camera.distance<=10.8);
  const collision=await page.evaluate(()=>{
    const a=window.__THREE_JS_GAME__.app,h=a.__hub,p=h.scene.player,physics=h.scene.physics;
    const circles=h.group.userData.colliders.filter(c=>c.kind==='circle'&&c.radius>.6);
    const collider=circles.sort((u,v)=>Math.hypot(h.group.position.x+u.x-p.base.position.x,h.group.position.z+u.z-p.base.position.z)-Math.hypot(h.group.position.x+v.x-p.base.position.x,h.group.position.z+v.z-p.base.position.z))[0];
    const center={x:h.group.position.x+collider.x,z:h.group.position.z+collider.z};
    physics.playerPosition.set(center.x,physics.playerPosition.y,center.z);
    p.body.position.set(center.x,p.body.position.y,center.z);
    p.base.position.set(center.x,p.base.position.y,center.z);
    const resolved=h.resolvePlayerCollision();
    const distance=Math.hypot(p.base.position.x-center.x,p.base.position.z-center.z);
    return {count:h.group.userData.colliders.length,resolved,distance,required:collider.radius+.62,bodySynced:p.body.position.x===p.base.position.x&&p.body.position.z===p.base.position.z,physicsSynced:physics.playerPosition.x===p.base.position.x&&physics.playerPosition.z===p.base.position.z};
  });
  assert.ok(collision.count>40,'solid hub meshes expose collision volumes');
  assert.equal(collision.resolved,true);
  assert.ok(collision.distance>=collision.required-.01,'runtime player hook pushes Glorb out of a solid hub mesh');
  assert.ok(collision.bodySynced&&collision.physicsSynced,'collision correction persists in the recovered physics controller');
  await page.evaluate(async()=>{
    const a=window.__THREE_JS_GAME__.app,p=a.__hub.scene.player,physics=a.__hub.scene.physics,spawn=a.__hub.scene.getPoint('Spawn').position;
    physics.playerPosition.copy(spawn);p.body.position.copy(spawn);p.base.position.copy(spawn);
    await new Promise(resolve=>setTimeout(resolve,80));
  });
  await page.screenshot({path:'test-results-hub/arrival.png'});
  await page.keyboard.down('KeyW');
  await page.waitForTimeout(900);
  await page.keyboard.up('KeyW');
  const moved=await snapshot();
  assert.ok(Math.hypot(moved.position.x-hub.position.x,moved.position.z-hub.position.z)>1,'Hub movement works');
  assert.equal(moved.time,hub.time);
  assert.equal(moved.paint,hub.paint);
  await page.getByRole('button',{name:'Enter Level One',exact:true}).click();
  await expect(page.getByRole('button',{name:"Let's paint",exact:true})).toBeVisible();
  assert.equal((await snapshot()).camera.elevation,hub.camera.elevation,'Camera stays original until game starts');
  await page.getByRole('button',{name:"Let's paint",exact:true}).click();
  await page.keyboard.down('KeyW');
  await page.waitForTimeout(900);
  await page.keyboard.up('KeyW');
  const level=await snapshot();
  assert.equal(level.hub,false);
  assert.equal(level.camera.elevation,22);
  assert.ok(level.time>0);
  await page.screenshot({path:'test-results-hub/level-one.png'});
  await page.getByRole('button',{name:'Return to hub',exact:true}).click();
  await expect(page.getByRole('button',{name:'Continue Level One',exact:true})).toBeVisible();
  const returned=await snapshot();
  await page.waitForTimeout(1100);
  const resting=await snapshot();
  assert.deepEqual(returned.camera,hub.camera);
  assert.equal(resting.time,returned.time);
  assert.equal(resting.health,returned.health);
  assert.equal(resting.paint,returned.paint);
  await page.screenshot({path:'test-results-hub/return.png'});
  await page.getByRole('button',{name:'Continue Level One',exact:true}).click();
  await page.waitForTimeout(250);
  const continued=await snapshot();
  assert.equal(continued.phase,'playing');
  assert.equal(continued.camera.elevation,22);
  assert.ok(continued.time>=returned.time);
  await page.setViewportSize({width:430,height:900});
  await page.waitForTimeout(250);
  assert.equal((await snapshot()).camera.elevation,22);
  await page.getByRole('button',{name:'Return to hub',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(350);
  assert.ok((await snapshot()).camera.elevation < 4.1);
  await page.screenshot({path:'test-results-hub/entrance.png'});
  await page.keyboard.down('KeyW');
  await page.waitForFunction(()=>!window.__THREE_JS_GAME__.app.__hub.active,null,{timeout:7000});
  await page.keyboard.up('KeyW');
  assert.equal((await snapshot()).phase,'playing');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({hub,collision,moved,level,returned,continued,errors},null,2));
} finally {await browser.close();}
